.rubocop.yml, app/services/concerns/can_load_file_to_aws.rb, app/services/reports/epr_export_service.rb, config/application.rb, lib/tasks/reports.rake, spec/services/reports/epr_export_service_spec.rb
From: https://eaflood.atlassian.net/browse/RUBY-866
Add rake task and main service code for EPR reports
=> Add epr rake task and service

config/schedule.rb
From: https://eaflood.atlassian.net/browse/RUBY-866
=> Schedule EPR export

app/models/reports/epr_serializer.rb, app/presenters/reports/epr_presenter.rb, app/services/reports/epr_export_service.rb, config/locales/en.yml, config/locales/time_formats.yml, spec/models/reports/epr_serializer_spec.rb, spec/presenters/reports/epr_presenter_spec.rb, spec/services/reports/epr_export_service_spec.rb
From: https://eaflood.atlassian.net/browse/RUBY-866
Implement EPR serializer and presenter to generate a CSV file with required information.
=> Add EPR export serializer and persenter

app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb, app/views/shared/_back.html.erb, app/views/shared/_validation_errors.html.erb, config/locales/en.yml, spec/features/devise/forgotten_password_feature_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1569
Note that this doesn't include the Invite users pages, they will be covered in: https://eaflood.atlassian.net/browse/RUBY-1504
=> Styling: Devise pages

app/views/admin/enrollment_exemptions/show/_comment_history.html.erb, app/views/admin/enrollment_exemptions/show/_main.html.erb
https://eaflood.atlassian.net/browse/RUBY-1494
- Set a consistent width for  the table columns
- Adds IDs to the table elements
=> Styling:  View Registration - Enhancements

app/views/layouts/flood_risk_engine.html.erb, config/initializers/assets.rb, spec/features/admin/new_registration_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1581
Here we enable the New Registration journey from within the Back Office
=> Styling: New Registration

app/models/address.rb, config/locales/activemodel.yml, spec/features/edit_address_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1495?focusedCommentId=332108
Here we use the engine's postcode validator to ensure the user enters a valid postcode
=> Validate the postcode format

config/locales/enrollments/correspondence_contacts.en.yml, config/locales/enrollments/organisations.en.yml, config/locales/enrollments/secondary_contacts.en.yml
https://eaflood.atlassian.net/browse/RUBY-1496?focusedCommentId=332267
=> Update form headings to match their context

app/models/enrollment_exemption.rb, config/locales/en.yml, spec/models/enrollment_exemption_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1499?focusedCommentId=334427
=> Validate the length of the comment's content

app/views/admin/enrollment_exemptions/resend_approval_email/new.html.erb
https://eaflood.atlassian.net/browse/RUBY-1603?focusedCommentId=334501
=> Add warning text to Resend email page

app/views/admin/users/_role_help.html.erb, config/locales/user_roles.en.yml
- Remove erroneous copy-paste text
- Remove 'in-progress' from roles help
https://eaflood.atlassian.net/browse/RUBY-1503?focusedCommentId=335142
=> Edit user: text changes

app/views/shared/_validation_errors.html.erb, config/locales/en.yml
https://eaflood.atlassian.net/browse/RUBY-1504?focusedCommentId=335151
=> Add a title to the generic validation error page to fix aria issue

app/controllers/admin/enrollment_exemptions/in_progress_controller.rb, config/locales/admin/enrollment_exemptions/in_progress.yml, config/locales/admin/enrollment_exemptions/show.en.yml, spec/features/in_progress_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1601?focusedCommentId=334440
=> Change 'In Progress' to 'In progress'

config/initializers/secure_headers.rb
- Inspired by:
https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/main/config/initializers/secure_headers.rb
- Relates to:
https://eaflood.atlassian.net/browse/RUBY-1468
=> Update the content security policy

Gemfile.lock
Bug fix: removing partner causes an error
https://eaflood.atlassian.net/browse/RUBY-1610
=> Bump the engine

app/views/registration_approved_mailer/approved.html.erb, app/views/registration_approved_mailer/approved.text.erb
https://eaflood.atlassian.net/browse/RUBY-1665?focusedCommentId=356316
=> Add NCCC email address to salmonid approved email template

app/services/prepare_enrollment_export_report.rb, config/environments/test.rb, spec/jobs/enrollment_export_job_spec.rb
fix for export bug
https://eaflood.atlassian.net/browse/RUBY-1910
=> [1910] Fix export bug

config/initializers/email_spec.rb
https://eaflood.atlassian.net/browse/RUBY-2434
https://eaflood.atlassian.net/browse/RUBY-2317
=> Adjust email_spec fix for Jenkins

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-2535
=> Version 2.1.0

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3029
=> Release v2.1.2

config/locales/admin/enrollment_exemptions/show/main.en.yml
https://eaflood.atlassian.net/browse/RUBY-3027
=> Change water management area label text

README.md
https://eaflood.atlassian.net/browse/RUBY-3027
=> Add Geospatial queries section to README.md

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-3090
=> Release v2.1.3

CHANGELOG.md
https://eaflood.atlassian.net/browse/RUBY-4025
=> Version 2.1.7
