DEFRA/flood-risk-back-office

Gemfile
Gemfile.lock
Procfile
README.md

When the app was first built there were no environments in which to deploy it. So the team used Heroku whilst they waited for them to become available.
The heroku apps are no longer used and hence there is no longer a need to maintain anything related to Heroku in the project.

Remove heroku from repo

---

.travis.yml
README.md
config/database.travis.yml

Now we have made the repository public there are a number of CI tools we can integrate
- [Codeclimate](https://codeclimate.com)
- [Hakiri](https://hakiri.io/)
- [Travis CI](https://travis-ci.com)
This change covers the updates necessary to integrate with these services, and badges! 😀

Integrate CI tools with repo

---

app/assets/stylesheets/application.css.scss

Include the application.scss from the engine. This lets us use shared styles like the privacy policy date styling.

Inherit engine styles

---

Gemfile

The original code for the github changelog generator entry came from [Waste Carriers](https://github.com/DEFRA/waste-carriers-back-office). In the original entry its not in the `development` group but in the main group. A note explains this should be in the `development` group, but due to an error caused by the gem when deploying to heroku, it was moved to the main group.
Well, we're not deploying to heroku anymore so PR #227 added it to the `development` group!
🤦 Well guess what happened when we then deployed this to our environments!?
So it seems the original comment was half right. Though it should be in the development group, putting the entry there breaks any deployment.

Move github changelog generator to main group

---

Gemfile.lock
config/initializers/area_lookup.rb

https://eaflood.atlassian.net/browse/RUBY-484
We have switched the FRAE service to use the gem [defra-ruby-area](https://github.com/DEFRA/defra-ruby-area) instead of [ea-area_lookup](https://github.com/DEFRA/ea-area_lookup). This means we need to update the engine (where the gem is added as a dependency and the logic sits) and remove the old gem's initializer (the new gem doesn't need one).

Migrate area lookup to defra-ruby-area

---

lib/tasks/lookups.rake
spec/lib/tasks/lookups_spec.rb

Reverts DEFRA/flood-risk-back-office#155
https://eaflood.atlassian.net/browse/RUBY-604
We spotted an issue after adding the `from_site_address` scope to the query used in the automated job to update the Area on site locations that are missing one.
We added the scope to ensure we were only updating locations linked to site addresses, but when testing the job we spotted
- there is an existing bug in the service which means the address type is never set to anything other than `:primary`
- locations only get created for site addresses
To fix the area lookup just means reverting the introduction of the scope in the back office hence this change.

Revert "Add scope on site addresses to Area Lookup"

---

config/initializers/01_airbrake.rb

The previous team took the decision to not activate airbrake in non-production environments, no doubt to reduce noise.
We on the other hand value having it enabled in all environments as it might highlight issues we haven't spotted. It also reduces the differences between the app running in production, and running in other environments.
On that last point PR #152 added a rake task which when run will update the area for enrollments missing it. We thought all was fine until we tried to run it in an environment where `RAILS_ENV=production`.
We get an error caused by the `Airbrake.close` line, something we would not have com across becase Airbrake is not enabled when running locally.
So for this reason we're making these changes, which bring the config more inline with our other services, …

Alter airbrake config to allow use in development

---

config/schedule.rb

https://eaflood.atlassian.net/browse/RUBY-604
When trying to test the job in our AWS environments it didn't run. After some investigation spotted that its because the default log path does not actually match our environment.
For 'reasons' even though the project is called `flood-risk-back-office` the folder created in the environment is  `flood-risk-activity-exemption-back-office`. Hence the path did not exist so the cron job would fail when ran.
This fix should sort the problem.

Fix default whenever log path

---

lib/close_airbrake.rb

To ensure errors are reported by Airbrake when a rake task fails we need
to tell Airbrake to close before the exit the task. This is because
Airbrake operates asynchronously, queuing up the notifications to send rather
than forcing the app to wait.
However there is an issue when calling `Airbrake.close` in the test
environment. The test suite will complain about airbrake being closed already
when running. Since there is no way in version 5.8 to ask Airbrake if it is
already closed or to reopen it before every test, this check prevents the test
suite from complaining.
We could have just put the line `Airbrake.close unless Rails.env.test?` in
each rake task, but we wanted to record these notes but just in one place.

Add Close Airbrake lib

---

config/locales/time_formats.yml

Since the formatting of dates is done authomatically by i18n, we want to make sure that the format is available for both Time and Date objects, so we don't need to add a custom rule in our code

Add format year_month_day_hyphens for time objects

---

app/services/read_from_aws_s3.rb

https://eaflood.atlassian.net/browse/RUBY-866
We have been tasked with generating an export of data from the service for the Electronic Public Register (EPR). This is exactly the same thing we have done for [Waste Exemptions](https://github.com/DEFRA/ruby-services-team/tree/master/services/wex) and [Waste Carriers](https://github.com/DEFRA/ruby-services-team/tree/master/services/wcr) and as such we brought in the code we used there, including our gem [defra-ruby-aws](https://github.com/DEFRA/defra-ruby-aws).
PR #189 handled that. But the project already has code for dealing with AWS and it seems something has gotten mixed up in the dependencies.
It seems we can still generate files and upload them to AWS. But when we try and retrieve them we get an error.
```bash
ArgumentError (expected …
```

Fix issue caused by API change

---

config/environments/development.rb

We have only recently identified this issue when working locally with the application. In the back office when an enrollment is selected there are a number of options which can change its status
- approve
- reject
- withdraw
- in progress
Even **Change status** where you can pick what status you want it to be!
Behind they scenes they are all a series of controllers that inherit `ChangeStatusBaseController`.
What we have found is that in our AWS environments everything is fine. When you select one of these e.g. **Withdraw**, and complete the action you are returned to the previously selected enrollment details page.
Locally though, this is not the case. It tries to redirect you to `http://localhost:3000/admin/enrollment_exemptions/3`.
Having looked into the issue we believe it originates …

Update default port number in development.rb

---

Gemfile.lock
config/initializers/defra_ruby_email.rb
config/initializers/flood_risk_engine.rb
config/routes.rb

Currently the [Waste Exemptions service](https://github.com/DEFRA/waste-exemptions-engine/pull/112) and the [Waste Carriers Frontend](https://github.com/DEFRA/waste-carriers-frontend/pull/227) have the ability to intercept and play back the details of the last email sent.
This feature is only enabled in our non-production environments and is used as part of our acceptance tests. However our QA @andrewhick has rightly pointed out that the functionality is inconsistent across our services.
Waste Exemptions has it throughout, Waste Carriers only has it in the old app, and Flood Risk Activity Exemptions doesn't have it at all. This makes writing and maintaining acceptance tests across the 3 services difficult and inconsistent so we have been asked to resolve the issue.
Rather than duplicate …

Enable defra-ruby-email in the project

---

Gemfile
Gemfile.lock

We have updated the default branch in the engine to `main` as part of our work to phase out use of `master`.
This means we also need to update the reference in our Gemfile.

Switch frae engine branch reference to master

---

Gemfile.lock

https://eaflood.atlassian.net/browse/RUBY-1099
web-ops have asked us to set the encryption for everything uploaded going forward to `AWS:KMS`. This updates the project to a version of [defra-ruby-aws](https://github.com/DEFRA/defra-ruby-aws/pull/20) that uses it.

Update defra-ruby-aws to AWS:KMS version

---

Gemfile.lock
config/initializers/defra_ruby_aws.rb

https://eaflood.atlassian.net/browse/RUBY-1156
In PR #238 recently we updated [defra-ruby-aws](https://github.com/DEFRA/defra-ruby-aws) to a version that encrypted our uploads using AWS:KMS instead of AES256.
It turns out that our 3rd parties are unable to decrypt those files using this new encryption method. To allow them to is going to take some reconfiguration of our S3 buckets and that will impact a number of users. So we need to revert the change.
However rather than going back to the previous version of the gem we have updated it to make switching between encryption methods configurable. This updates the back-office to use the updated gem and prepare it for being able to switch using config in the future.

Update defra-ruby-aws to encryption configurable

---

Gemfile
Gemfile.lock
app/services/concerns/can_load_file_to_aws.rb
app/services/reports/epr_export_service.rb
spec/services/reports/epr_export_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1240
We used to upload to the root but now we have to upload to an EPR subfolder.
All other exports should still go to the root.
Implementation of this involved updating defra-ruby-aws.

Upload EPR exports to EPR folder

---

app/views/admin/enrollment_exemptions/index.html.erb
config/locales/admin/enrollment_exemptions/index/enrollment_exemptions.en.yml

This addresses QA feedback that the Search and Select menus didn't have label text. 
https://eaflood.atlassian.net/browse/RUBY-1477

Add hidden labels to the Search and Select menus

---

app/views/shared/_flash_alerts.html.erb

Relates to:
https://eaflood.atlassian.net/browse/RUBY-1569?focusedCommentId=329538
Here we ensure that there `aria-labelled-by` has a corresponding `ID`

Add an ID attribute to match the aria-labelled by

---

app/views/admin/users/index.html.erb
app/views/layouts/_navbar.html.erb
config/locales/users.en.yml
spec/features/nav_menu_feature_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1502
- Take the question mark off ‘Invitation accepted' column and rename the enabled column to 'Status'
- Add accepted into the ‘Invitation accepted’ column, rather than the dash.
- Make green invite button be a link under the H1
- H1 needs to say ‘Admin users’
- Invite users link removed from header menu
- Ensure there are no empty table headers (actions column)

Styling: View users - Enhancements

---

Gemfile
Gemfile.lock
app/controllers/admin/enrollments_controller.rb
app/forms/admin/enrollment_exemptions/base_change_state_form.rb
config/initializers/flood_risk_engine.rb
config/initializers/paper_trail.rb
config/initializers/pundit.rb
config/initializers/reform.rb
spec/controllers/admin/enrollments_controller_spec.rb
spec/factories/enrollments_factory.rb
spec/factories/flood_risk_engine_contacts_factory.rb
spec/factories/submitted_enrollments_factory.rb
spec/features/new_registration_spec.rb
spec/models/enrollment_export_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1592
There are some components (notably Reform) that have been removed from the engine but are still being refactored out of the back office. So I've added some things back in temporarily.
Also noticed that we'll need to change the way we store the AD status in the engine - this will be done in an upcoming PR.

Update engine without legacy code

---

app/models/address.rb
config/locales/en.yml
spec/features/edit_address_spec.rb
spec/models/address_spec.rb

Relates to:
https://eaflood.atlassian.net/browse/RUBY-1495?focusedCommentId=332672
There is a database constraint on the postcode column - max 8 chars length
Previously we used the postcode validator to check the format of the postcode.
This opened a can of worms because it also does a postcode look up.
As this form is to be used by NCCC to fix incorrect addresses, we are
going with a manual version.

Validate the postcode length

---

app/controllers/admin/enrollment_exports_controller.rb
app/models/enrollment_export.rb
spec/features/export_spec.rb
spec/models/enrollment_export_spec.rb

**Set the default To Date on the Export form (this was here previously)**
https://eaflood.atlassian.net/browse/RUBY-1497
**Fix bug that cause the file to be incorrectly uploaded to S3**

Enrollment Export Repairs

---

app/controllers/admin/users_controller.rb
app/policies/user_policy.rb
app/views/admin/users/index.html.erb
config/locales/users.en.yml
config/routes.rb
spec/features/admin/list_users_feature_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1596
Here we introduce a toggle to view Enabled / All users
Have removed the 'policy_scope' as it does some strange caching
(that I don't really understand)

Improve UX for list of back office users

---

app/controllers/admin/enrollment_exemptions/approve_controller.rb
app/controllers/admin/enrollment_exemptions/change_status_controller.rb
app/controllers/admin/enrollment_exemptions/deregister_controller.rb
app/controllers/admin/enrollment_exemptions/in_progress_controller.rb
app/controllers/admin/enrollment_exemptions/reject_controller.rb
app/controllers/admin/enrollment_exemptions/resend_approval_email_controller.rb
app/controllers/admin/enrollment_exemptions/withdraw_controller.rb
app/models/enrollment_exemption.rb
app/views/admin/enrollment_exemptions/show/_comment_history.html.erb
spec/features/approve_spec.rb
spec/features/change_status_spec.rb
spec/features/deregister_spec.rb
spec/features/in_progress_spec.rb
spec/features/reject_spec.rb
spec/features/resend_approval_email_spec.rb
spec/features/withdraw_spec.rb
spec/models/enrollment_exemption_spec.rb

Here we store the user_id in the comments table when an action is performed on a registration. 
Then we display the user's email in the comment section
**Approval**
https://eaflood.atlassian.net/browse/RUBY-1499?focusedCommentId=334666

Prepend user email to comments

---

app/views/admin/enrollment_exemptions/approve/new.html.erb
app/views/admin/enrollment_exemptions/change_status/new.html.erb
app/views/admin/enrollment_exemptions/deregister/new.html.erb
app/views/admin/enrollment_exemptions/in_progress/new.html.erb
app/views/admin/enrollment_exemptions/index.html.erb
app/views/admin/enrollment_exemptions/reject/new.html.erb
app/views/admin/enrollment_exemptions/resend_approval_email/new.html.erb
app/views/admin/enrollment_exemptions/show.html.erb
app/views/admin/enrollment_exemptions/withdraw/new.html.erb
app/views/admin/enrollment_exports/index.html.erb
app/views/admin/users/edit.html.erb
app/views/admin/users/edit_disable.html.erb
app/views/admin/users/index.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb
app/views/invitations/edit.html.erb
app/views/invitations/new.html.erb

- Here we update the page titles to work with the changes in this commit:
https://github.com/DEFRA/flood-risk-back-office/commit/c80ddecbefdb8a5f95a1a7ce085bf5e448bac267
Relates to:
https://eaflood.atlassian.net/browse/RUBY-1499?focusedCommentId=334394

Fix the html page <title>

---

app/views/layouts/_navbar.html.erb
config/initializers/devise.rb

- :delete requires jQuery, so the sign out link broke when we removed jQuery

Sign out via :get instead of :delete

---

Gemfile.lock
config/initializers/flood_risk_engine.rb

https://eaflood.atlassian.net/browse/RUBY-1506
Previously we just validated the format of the Companies House number to see if it looked about right. Now we
use our validation gem to send it off to the Companies House API to check if it actually belongs to an active company.
---
Depends on https://github.com/DEFRA/flood-risk-engine/pull/435 – CI will fail until this engine update is merged in

Add config to validate with Companies House

---

app/controllers/invitations_controller.rb
spec/features/devise/invite_user_feature_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1504?focusedCommentId=336619
- When a user is invited, there is no validation to check whether they
already have an open invitation, and they are assigned another role
- Here we avoid assigning the user a new role, if they already have one
- Ideally we would to this with a validation, but the roles are assigned
willy-nilly in the invitations controller

Avoid assigning an invited user multiple roles

---

Gemfile.lock
config/initializers/flood_risk_engine.rb

https://eaflood.atlassian.net/browse/RUBY-1604
This configures the back office to set the assistance mode of any registrations submitted here as 'assisted'.

Update engine and configure default assistance mode

---

Gemfile
Gemfile.lock
app/services/transient_registration_cleanup_service.rb
config/application.rb
config/schedule.rb
db/schema.rb
lib/tasks/cleanup.rake
spec/lib/tasks/cleanup_spec.rb
spec/schedule_spec.rb
spec/services/transient_registration_cleanup_service_spec.rb

https://eaflood.atlassian.net/browse/RUBY-1685
We want to clean up old transient_registration records that have been sitting around for more than 30 days.
---
Depends on https://github.com/DEFRA/flood-risk-engine/pull/448

Remove old transient_registration records

---

config/initializers/session_store.rb
config/schedule.rb
spec/schedule_spec.rb

- This is an attempt to fix session replay bug that came up in the PEN test (3.1.1)
- The engine enforces use of the activerecord-session_store gem,
which should use a database table to store the session data.
- But, the app was using the cookie_store instead. The database table is there,
but unused.
- To prevent the databased table growing too large, we are adding a scheduled t
`db:sessions:trim` to clean up sessions that have been unused for 30 days.
More info: https://github.com/rails/activerecord-session_store
Relates to: https://eaflood.atlassian.net/browse/RUBY-1715

Prefer active_record_store over cookie_store

---

Gemfile
Gemfile.lock

Deploys to dev are failing, this aims to remedy this by including gems/libraries no longer included in ruby 3.1
https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp/70500221#70500221

[1910] adds missing libraries

---

app/services/concerns/can_load_file_to_aws.rb

https://eaflood.atlassian.net/browse/RUBY-2831
- For some reason rails autoloader is broken/disabled in this FRAE project and libraries have to be loaded manually
- A short-term solution has been applied and the task to refactor the autoloader added to a tech debt list

[RUBY-2831] temporarily manual file loading till autoloader is fixed
